import collections

defaults = collections.OrderedDict()

defaults['import_eM'] = collections.OrderedDict()
defaults['import_eM']['constobsid']            = True
defaults['import_eM']['scanreindexgap_s']      = 15.0
defaults['import_eM']['antenna']               = ''
defaults['import_eM']['timeaverage']           = True
defaults['import_eM']['timebin']               = '4s'
defaults['import_eM']['chanaverage']           = False
defaults['import_eM']['chanbin']               = 4
defaults['import_eM']['usewtspectrum']         = False
defaults['import_eM']['run_hanning']           = 'auto'
defaults['import_eM']['ms2mms']                = False

defaults['aoflagger'] = collections.OrderedDict()
defaults['aoflagger']['fields']               = 'all'
defaults['aoflagger']['separate_bands']       = True

defaults['flag_apriori'] = collections.OrderedDict()
defaults['flag_apriori']['do_quack']          = True

defaults['average'] = collections.OrderedDict()
defaults['average']['width']                  = 4
defaults['average']['datacolumn']             = 'data'
defaults['average']['timerange']              = ''
defaults['average']['scan']                   = ''
defaults['average']['antenna']                = ''

defaults['plot_data'] = collections.OrderedDict()
defaults['plot_data']['num_proc']             = 1

defaults['init_models'] = collections.OrderedDict()
defaults['init_models']['calibrator_models']  = 'calibrator_models/'

defaults['bandpass'] = collections.OrderedDict()
defaults['bandpass']['delay_tablename']       = 'bpcal_d.K0'
defaults['bandpass']['delay_solint']          = '180s'
defaults['bandpass']['delay_combine']         = 'spw'
defaults['bandpass']['delay_prev_cal']        = []
defaults['bandpass']['delay_interp']          = 'linear'
defaults['bandpass']['delay_spw']             = ['*','innerchan']
defaults['bandpass']['delay_minblperant']     = 3
defaults['bandpass']['delay_minsnr']          = 2
defaults['bandpass']['phase_tablename']       = 'bpcal_p.G0'
defaults['bandpass']['phase_solint']          = 'int'
defaults['bandpass']['phase_prev_cal']        = ['bpcal_d.K0']
defaults['bandpass']['phase_interp']          = 'linear'
defaults['bandpass']['phase_combine']         = ''
defaults['bandpass']['phase_spw']             = ['*','innerchan']
defaults['bandpass']['phase_minblperant']     = 3
defaults['bandpass']['phase_minsnr']          = 2
defaults['bandpass']['ap_tablename']          = 'bpcal_ap.G1'
defaults['bandpass']['ap_solint']             = '32s'
defaults['bandpass']['ap_prev_cal']           = ['bpcal_d.K0', 'bpcal_p.G0']
defaults['bandpass']['ap_interp']             = 'linear'
defaults['bandpass']['ap_combine']            = ''
defaults['bandpass']['ap_spw']                = ['*','innerchan']
defaults['bandpass']['ap_minblperant']        = 3
defaults['bandpass']['ap_minsnr']             = 2
defaults['bandpass']['bp_tablename']          = 'bpcal.B0'
defaults['bandpass']['bp_solint']             = 'inf'
defaults['bandpass']['bp_combine']            = 'field,scan'
defaults['bandpass']['bp_interp']             = 'nearest,cubicflag'
defaults['bandpass']['bp_spw']                = ['*','']
defaults['bandpass']['bp_uvrange']            = ''
defaults['bandpass']['bp_fillgaps']           = 4
defaults['bandpass']['bp_solnorm']            = True
defaults['bandpass']['bp_prev_cal']           = ['bpcal_d.K0', 'bpcal_p.G0', 'bpcal_ap.G1']
defaults['bandpass']['apply_calibrators']     = ['bpcal.B0']
defaults['bandpass']['apply_targets']         = ['bpcal.B0']

defaults['flag_tfcrop'] = collections.OrderedDict()
defaults['flag_tfcrop']['mode']               = 'tfcrop'
defaults['flag_tfcrop']['antenna']            = ''
defaults['flag_tfcrop']['scan']               = ''
defaults['flag_tfcrop']['spw']                = ''
defaults['flag_tfcrop']['correlation']        = 'ABS_ALL'
defaults['flag_tfcrop']['ntime']              = '90min'
defaults['flag_tfcrop']['combinescans']       = True
defaults['flag_tfcrop']['datacolumn']         = 'corrected'
defaults['flag_tfcrop']['winsize']            = 3
defaults['flag_tfcrop']['timecutoff']         = 4.0
defaults['flag_tfcrop']['freqcutoff']         = 3.0
defaults['flag_tfcrop']['maxnpieces']         = 1
defaults['flag_tfcrop']['usewindowstats']     = 'sum'
defaults['flag_tfcrop']['halfwin']            = 3
defaults['flag_tfcrop']['extendflags']        = True
defaults['flag_tfcrop']['action']             = 'apply'
defaults['flag_tfcrop']['display']            = ''
defaults['flag_tfcrop']['flagbackup']         = True

defaults['delay'] = collections.OrderedDict()
defaults['delay']['use_fringefit']            = False
defaults['delay']['tablename']                = 'delay.K1'
defaults['delay']['solint']                   = '300s'
defaults['delay']['combine']                  = 'spw'
defaults['delay']['prev_cal']                 = ['bpcal.B0']
defaults['delay']['interp']                   = 'linear'
defaults['delay']['spw']                      = ['*','innerchan']
defaults['delay']['zerorates']                = True
defaults['delay']['minblperant']              = 3
defaults['delay']['minsnr']                   = 3
defaults['delay']['apply_calibrators']        = ['bpcal.B0','delay.K1']
defaults['delay']['apply_targets']            = []

defaults['gain_p_ap'] = collections.OrderedDict()
defaults['gain_p_ap']['p_tablename']          = 'allcal_p.G0'
defaults['gain_p_ap']['p_prev_cal']           = ['bpcal.B0','delay.K1']
defaults['gain_p_ap']['p_solint']             = 'int'
defaults['gain_p_ap']['p_spw']                = ['*','innerchan']
defaults['gain_p_ap']['p_combine']            = ''
defaults['gain_p_ap']['p_interp']             = 'linear'
defaults['gain_p_ap']['p_minblperant']        = 3
defaults['gain_p_ap']['p_minsnr']             = 3
defaults['gain_p_ap']['ap_tablename']         = 'allcal_ap.G1'
defaults['gain_p_ap']['ap_prev_cal']          = ['bpcal.B0','delay.K1','allcal_p.G0']
defaults['gain_p_ap']['ap_solint']            = '32s'
defaults['gain_p_ap']['ap_spw']               = ['*','innerchan']
defaults['gain_p_ap']['ap_combine']           = ''
defaults['gain_p_ap']['ap_interp']            = 'linear'
defaults['gain_p_ap']['ap_minblperant']       = 3
defaults['gain_p_ap']['ap_minsnr']            = 3
defaults['gain_p_ap']['apply_calibrators']    = ['bpcal.B0','delay.K1','allcal_p.G0','allcal_ap.G1']
defaults['gain_p_ap']['apply_targets']        = []

defaults['fluxscale'] = collections.OrderedDict()
defaults['fluxscale']['tablename']           = 'allcal_ap.G1_fluxscaled'
defaults['fluxscale']['ampcal_table']        = 'allcal_ap.G1'
defaults['fluxscale']['apply_calibrators']   = ['bpcal.B0','delay.K1','allcal_p.G0','allcal_ap.G1_fluxscaled']
defaults['fluxscale']['apply_targets']       = []

defaults['bandpass_sp'] = collections.OrderedDict()
defaults['bandpass_sp']['bp_tablename']       = 'bpcal_sp.B1'
defaults['bandpass_sp']['bp_prev_cal']        = ['delay.K1','allcal_p.G0','allcal_ap.G1_fluxscaled']
defaults['bandpass_sp']['bp_solint']          = 'inf'
defaults['bandpass_sp']['bp_spw']             = ['*','']
defaults['bandpass_sp']['bp_combine']         = 'field,scan'
defaults['bandpass_sp']['bp_interp']          = 'nearest,cubicflag'
defaults['bandpass_sp']['bp_uvrange']         = ''
defaults['bandpass_sp']['bp_fillgaps']        = 8
defaults['bandpass_sp']['bp_solnorm']         = False
defaults['bandpass_sp']['apply_calibrators']  = ['delay.K1','allcal_p.G0','allcal_ap.G1_fluxscaled','bpcal_sp.B1']
defaults['bandpass_sp']['apply_targets']      = []

defaults['gain_amp_sp'] = collections.OrderedDict()
defaults['gain_amp_sp']['ap_tablename']       = 'allcal_ap.G3'
defaults['gain_amp_sp']['ap_prev_cal']        = ['delay.K1','allcal_p.G0','bpcal_sp.B1']
defaults['gain_amp_sp']['ap_solint']          = '32s'
defaults['gain_amp_sp']['ap_spw']             = ['*','innerchan']
defaults['gain_amp_sp']['ap_combine']         = ''
defaults['gain_amp_sp']['ap_interp']          = 'linear'
defaults['gain_amp_sp']['ap_minblperant']     = 3
defaults['gain_amp_sp']['ap_minsnr']          = 3
defaults['gain_amp_sp']['p_scan_tablename']   = 'phscal_p_scan.G3'
defaults['gain_amp_sp']['p_scan_prev_cal']    = ['delay.K1','bpcal_sp.B1']
defaults['gain_amp_sp']['p_scan_solint']      = 'inf'
defaults['gain_amp_sp']['p_scan_spw']         = ['*','innerchan']
defaults['gain_amp_sp']['p_scan_combine']     = ''
defaults['gain_amp_sp']['p_scan_interp']      = 'linear'
defaults['gain_amp_sp']['p_scan_minblperant'] = 3
defaults['gain_amp_sp']['p_scan_minsnr']      = 3
defaults['gain_amp_sp']['ap_scan_tablename']  = 'phscal_ap_scan.G3'
defaults['gain_amp_sp']['ap_scan_prev_cal']   = ['delay.K1','bpcal_sp.B1','allcal_p.G0']
defaults['gain_amp_sp']['ap_scan_solint']     = 'inf'
defaults['gain_amp_sp']['ap_scan_spw']        = ['*','innerchan']
defaults['gain_amp_sp']['ap_scan_combine']    = ''
defaults['gain_amp_sp']['ap_scan_interp']     = 'linear'
defaults['gain_amp_sp']['ap_scan_minblperant']= 3
defaults['gain_amp_sp']['ap_scan_minsnr']     = 3
defaults['gain_amp_sp']['apply_calibrators']  = ['delay.K1','allcal_p.G0','bpcal_sp.B1','allcal_ap.G3']
defaults['gain_amp_sp']['apply_targets']      = []

defaults['applycal_all'] = collections.OrderedDict()
defaults['applycal_all']['apply_calibrators'] = ['delay.K1','allcal_p.G0','bpcal_sp.B1','allcal_ap.G3']
defaults['applycal_all']['apply_targets']     = ['delay.K1','bpcal_sp.B1','phscal_p_scan.G3','phscal_ap_scan.G3']

defaults['flag_rflag'] = collections.OrderedDict()
defaults['flag_rflag']['mode']                = 'rflag'
defaults['flag_rflag']['sources']             = 'targets'
defaults['flag_rflag']['antenna']             = ''
defaults['flag_rflag']['scan']                = ''
defaults['flag_rflag']['spw']                 = ''
defaults['flag_rflag']['correlation']         = 'ABS_LL,RR'
defaults['flag_rflag']['ntime']               = 'scan'
defaults['flag_rflag']['combinescans']        = False
defaults['flag_rflag']['datacolumn']          = 'corrected'
defaults['flag_rflag']['timedevscale']        = 4.0
defaults['flag_rflag']['freqdevscale']        = 4.0
defaults['flag_rflag']['extendflags']         = False
defaults['flag_rflag']['action']              = 'apply'
defaults['flag_rflag']['display']             = ''
defaults['flag_rflag']['flagbackup']          = True

defaults['first_images'] = collections.OrderedDict()
defaults['first_images']['imsize']            = 1024
defaults['first_images']['niter']             = 200
defaults['first_images']['deconvolver']       = 'hogbom'
defaults['first_images']['nterms']            = 1
#defaults['first_images']['deconvolver']       = 'mtmfs'
#defaults['first_images']['nterms']            = 2
defaults['first_images']['weighting']         = 'briggs'
defaults['first_images']['robust']            = 0.5
defaults['first_images']['gain']              = 0.1
defaults['first_images']['nsigma']            = 5.0
defaults['first_images']['sidelobethreshold'] = 1.0
defaults['first_images']['noisethreshold']    = 8.0
defaults['first_images']['lownoisethreshold'] = 1.5
defaults['first_images']['minbeamfrac']       = 0.2
defaults['first_images']['growiterations']    = 25
defaults['first_images']['level0']            = 3.
