name: eMCP
channels:
- pkgw-forge
- conda-forge
- defaults
dependencies:
- casacore
- openmpi
- python=3.8
- numpy=1.23
- pip
- pip:
  - almatasks==1.5.2
  - aplpy==2.1.0
  - astropy==5.1.1
  - astroquery==0.4.6
  - casadata==2022.9.5
  - casampi==0.5.01
  - casaplotms==1.8.7
  - casaplotserver==1.4.6
  - casashell==6.5.2.26
  - casatasks==6.5.2.26
  - casatestutils==6.5.2.26
  - casatools==6.5.2.26
  - casaviewer==1.6.6
  - cmasher==1.6.3
  - ipython==8.6.0
  - matplotlib==3.6.1
  - python-casacore==3.5.2
  - scipy==1.9.3
