name: eMCP
channels:
  - pkgw-forge
  - conda-forge
  - defaults
dependencies:
  - aplpy
  - astropy
  - astroquery
  - casacore
  - ipython
  - matplotlib
  - numpy
  - python=3.7
  - python-casacore
  - scipy
#  - wsclean
