name: emcp
channels:
  - conda-forge
  - nodefaults
dependencies:
  - casacore=3.7.1
  - cmasher=1.9.2
  - ipython=8.36.0
  - libboost-python=1.86.0
  - matplotlib=3.10.3
  - mpi4py=4.0.3
  - numpy=2.2.6
  - openmpi=5.0.7
  - pip=25.1.1
  - python=3.10.17
  - python-casacore=3.7.1
  - scipy=1.15.2
  - setuptools=80.8.0
  - pip
  - pip:
    - casaconfig==1.0.2
    - casatools==6.7.0.31
    - casatasks==6.7.0.31
    - casaplotms==2.6.2
    - casaviewer==2.3.2
    - casashell==6.7.0.31
    - casaplotserver==1.9.2
    - casatestutils==6.7.0.31
    - casatablebrowser==0.0.37
    - casalogger==1.0.21
    - casafeather==0.0.24
    - casampi==0.5.6
    - -e .
clean
