name: emcp
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - casacore=3.5
  - setuptools=75.8
  - astropy=5.1.1
  - astroquery=0.4.6
  - cmasher=1.6.3
  - ipython=8.6.0
  - matplotlib=3.6.1
  - python-casacore=3.5.2
  - protobuf=3.20
  - scipy=1.9.3
  - numpy=1.24.4
  - pip
  - pip:
    - casatools==6.7.0.31
    - casatasks==6.7.0.31
    - casaplotms==2.6.2
    - casaviewer==2.3.2
    - casashell==6.7.0.31
    - casaplotserver==1.9.2
    - casatestutils==6.7.0.31
    - casatablebrowser==0.0.37
    - casalogger==1.0.21
    - casafeather==0.0.24
    - casampi==0.5.6
    - aplpy==2.1.0
    - reproject==0.14.1
    - pyregion==2.3.0
    - git+https://github.com/e-merlin/eMERLIN_CASA_pipeline.git@casa6
