name: eMCP
channels:
- pkgw-forge
- conda-forge
- defaults
dependencies:
- aoflagger
- casacore
- python>=3.8, <3.10
- numpy=1.23.4
- pip
- pip:
- aplpy==2.1.0
- astropy==5.1.1
- astroquery==0.4.6
- ipython==8.6.0
- matplotlib==3.6.1
- python-casacore==3.5.2
- scipy==1.9.3
- cmasher==1.6.3
