# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: testpypi-publish

on:
  release:
    types: [draft]


permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:base
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    steps:
    - uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0
        set-safe-directory: true
    - name: Force directory safe
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip wheel setuptools setuptools-scm
        python3 -m pip install virtualenv
        python3 -m pip install build
    - name: Build package
      run: python3 -m build
    - name: Build bdist package
      run: python3 setup.py bdist_wheel
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
